### ISSUE TITLE
Bonjour-Reflector for RouterOS

### ISSUE THREAD

**Issue by brg3466** [nberlee/bonjour-reflector#35]
Hello,  thank you for the great work !   I  have CCR2xxx + CRS328 + 7 x cAP ax  running wifiwave2 CAPsMAN with vlans.  All on 7.11.2.  Just want to know whether it works if I run the container on the cAP ax  or it has to be on the main router CCR2xxxx  ?  Thank you !

**Comment by nberlee** [comment]
I answered here: https://forum.mikrotik.com/viewtopic.php?p=1024110#p1024110

Its fine either way, I have it on my router (CCR2004), but I also could have it somewhere else. but there are two main things to keep in mind.
The router on where bonjour-reflector runs should see all the multicast traffic and upstream ports should have unknown-multicast=yes. And you should not run multiple bonjour-reflectors in the same vlans.
